/**
 * Configuration types for the Field Service App
 * This config is generated by the spec-selector and consumed by the app
 */

export interface CustomFieldConfig {
  id: string
  name: string
  type: 'text' | 'number' | 'date' | 'checkbox' | 'rating' | 'dropdown'
  label: string
  required: boolean
  options?: string[]
}

export interface WorkflowStateConfig {
  id: string
  name: string
  color: string
  isCustom: boolean
}

export interface AuthConfig {
  method: 'basic' | 'pin-device' | 'magic-link' | 'oidc'
  mfaEnabled: boolean
  userManagementEnabled: boolean
  auditLoggingEnabled: boolean
}

export interface ConfigUser {
  id: string
  email: string
  name: string
  passwordHash?: string
  persona: string
  permissions: string[]
}

export interface AppConfig {
  version: string
  generatedAt: string | null

  features: {
    personas: string[]
    scenarios: string[]
  }

  customFields: {
    workOrder: CustomFieldConfig[]
  }

  workflowStates: WorkflowStateConfig[]

  constraints: {
    offlineFirst: boolean
    languages: string[]
    infrastructure: string
    syncUrl?: string
  }

  authentication?: AuthConfig

  users?: ConfigUser[]

  // Runtime metadata
  _configName?: string
  _active?: string
  _serverSettings?: {
    featureEditorUrl: string
    appUrl: string
  }
}
